// diamond-frontend/src/features/chatbot/Chatbot.jsx
// Full AI chatbot UI powered by the LangChain LCEL pipeline backend.
// Follow-up suggestion chips are dynamically generated by the LLM per response.

import { useState, useRef, useEffect, useCallback } from 'react';
import {
  MessageCircle, X, Send, Sparkles, Minimize2,
  RotateCcw, ChevronDown, AlertCircle, Loader2, Gem, Maximize2, CornerDownLeft,
} from 'lucide-react';
import { useChatbotStore } from '../../store/useChatbotStore';

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Render markdown-lite: **bold**, newlines → <br>. Sanitised inline only. */
function RichText({ text }) {
  const lines = String(text).split('\n');
  return (
    <>
      {lines.map((line, i) => {
        // Convert **bold** spans
        const parts = line.split(/(\*\*[^*]+\*\*)/g);
        const rendered = parts.map((part, j) =>
          part.startsWith('**') && part.endsWith('**')
            ? <strong key={j}>{part.slice(2, -2)}</strong>
            : part
        );
        return (
          <span key={i}>
            {rendered}
            {i < lines.length - 1 && <br />}
          </span>
        );
      })}
    </>
  );
}

// ── Message Bubble ─────────────────────────────────────────────────────────────

function MessageBubble({ message, onSuggestionClick, isExpanded }) {
  const isUser   = message.role === 'user';
  const isError  = !!message.isError;
  const chips    = (!isUser && Array.isArray(message.followUpSuggestions))
                    ? message.followUpSuggestions
                    : [];

  return (
    <div className={`flex ${isUser ? 'justify-end' : 'justify-start'} mb-4`}>

      {/* Assistant avatar */}
      {!isUser && (
        <div className="flex-shrink-0 w-8 h-8 rounded-2xl bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center mr-2 mt-0.5 shadow-sm">
          <Gem className="w-4 h-4 text-white" />
        </div>
      )}

      <div className={`flex flex-col gap-2 ${isExpanded ? 'w-full' : 'max-w-[82%]'}`}>
        {/* Bubble */}
        <div
          className={`
            rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm
            ${isExpanded ? 'text-base py-4 px-5' : ''}
            ${isUser
              ? 'bg-gradient-to-br from-sky-500 to-indigo-600 text-white rounded-br-sm'
              : isError
                ? 'bg-red-50 text-red-800 border border-red-200 rounded-bl-sm'
                : 'bg-white text-gray-800 border border-gray-100 rounded-bl-sm'
            }
          `}
        >
          {isError && (
            <div className="flex items-center gap-1.5 mb-1.5 text-red-600">
              <AlertCircle className="w-3.5 h-3.5 flex-shrink-0" />
              <span className="text-xs font-semibold">Something went wrong</span>
            </div>
          )}

          <RichText text={message.content} />

          <div className={`text-xs mt-2 ${isUser ? 'text-sky-200' : 'text-gray-400'}`}>
            {new Date(message.timestamp).toLocaleTimeString([], {
              hour: '2-digit', minute: '2-digit',
            })}
          </div>
        </div>

        {/* Dynamic follow-up suggestion chips (LLM-generated per response) */}
        {chips.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {chips.map((chip, i) => (
              <button
                key={i}
                onClick={() => onSuggestionClick(chip)}
                className="text-xs px-3 py-1.5 bg-sky-50 text-sky-700 border border-sky-200 rounded-full hover:bg-sky-100 hover:border-sky-300 transition-all font-medium text-left"
              >
                {chip}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* User avatar */}
      {isUser && (
        <div className="flex-shrink-0 w-8 h-8 rounded-2xl bg-gray-200 flex items-center justify-center ml-2 mt-0.5 text-xs font-bold text-gray-600">
          You
        </div>
      )}
    </div>
  );
}

// ── Typing Indicator ──────────────────────────────────────────────────────────

function TypingIndicator() {
  return (
    <div className="flex justify-start mb-4">
      <div className="flex-shrink-0 w-8 h-8 rounded-2xl bg-gradient-to-br from-sky-500 to-indigo-600 flex items-center justify-center mr-2 mt-0.5 shadow-sm">
        <Gem className="w-4 h-4 text-white" />
      </div>
      <div className="bg-white border border-gray-100 rounded-2xl rounded-bl-sm px-4 py-3 shadow-sm">
        <div className="flex items-center gap-2">
          <div className="flex gap-1">
            {[0, 150, 300].map((delay) => (
              <span
                key={delay}
                className="w-2 h-2 bg-sky-400 rounded-full animate-bounce"
                style={{ animationDelay: `${delay}ms` }}
              />
            ))}
          </div>
          <span className="text-xs text-gray-400">Thinking…</span>
        </div>
      </div>
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────────

export default function Chatbot() {
  const {
    isOpen, isMinimized,
    messages, isLoading, isTyping, error,
    openChatbot, closeChatbot, minimizeChatbot, restoreChatbot,
    sendMessage, clearConversation,
  } = useChatbotStore();

  const [inputValue, setInputValue]     = useState('');
  const [showScrollBtn, setShowScrollBtn] = useState(false);
  const [isExpanded, setIsExpanded]       = useState(false);

  const messagesEndRef       = useRef(null);
  const messagesContainerRef = useRef(null);
  const inputRef             = useRef(null);
  const textareaRef          = useRef(null);

  // Auto-scroll
  const scrollToBottom = useCallback((smooth = true) => {
    messagesEndRef.current?.scrollIntoView({ behavior: smooth ? 'smooth' : 'instant' });
  }, []);

  useEffect(() => {
    if (isOpen && !isMinimized) scrollToBottom();
  }, [messages, isTyping, isOpen, isMinimized, scrollToBottom]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen && !isMinimized) {
      setTimeout(() => inputRef.current?.focus(), 120);
    }
  }, [isOpen, isMinimized]);

  // Handle Escape key to close expanded view
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && isExpanded) {
        setIsExpanded(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isExpanded]);

  // Scroll-to-bottom button visibility
  const handleScroll = () => {
    const el = messagesContainerRef.current;
    if (!el) return;
    setShowScrollBtn(el.scrollHeight - el.scrollTop - el.clientHeight > 120);
  };

  // Auto-resize textarea
  const autoResize = () => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = 'auto';
    el.style.height = Math.min(el.scrollHeight, 120) + 'px';
  };

  const handleSend = () => {
    const text = inputValue.trim();
    if (!text || isLoading) return;
    setInputValue('');
    if (textareaRef.current) textareaRef.current.style.height = 'auto';
    sendMessage(text);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleSuggestionClick = (text) => {
    if (isLoading) return;
    sendMessage(text);
  };

  const handleClear = async () => {
    if (!window.confirm('Start a new conversation? History will be cleared.')) return;
    await clearConversation();
  };

  // Unread count for launcher badge
  const unreadCount = isOpen
    ? 0
    : Math.max(0, messages.filter((m) => m.role === 'assistant').length - 1);

  // ── Minimized pill ────────────────────────────────────────────────────────
  if (isOpen && isMinimized) {
    return (
      <button
        onClick={restoreChatbot}
        className="fixed bottom-6 right-6 z-50 flex items-center gap-2 px-5 py-3 bg-gradient-to-r from-sky-500 to-indigo-600 text-white rounded-full shadow-2xl hover:shadow-sky-400/40 transition-all duration-300 hover:scale-105"
      >
        <Gem className="w-4 h-4" />
        <span className="text-sm font-semibold">Diamond Expert</span>
        {isTyping && <Loader2 className="w-4 h-4 animate-spin" />}
      </button>
    );
  }

  return (
    <>
      {/* ── Launcher button ─────────────────────────────────────────────── */}
      {!isOpen && (
        <button onClick={openChatbot} className="fixed bottom-6 right-6 z-50 group" aria-label="Open chat assistant">
          <span className="absolute inset-0 rounded-full bg-sky-400 animate-ping opacity-20" />

          <div className="relative w-16 h-16 bg-gradient-to-br from-sky-500 to-indigo-600 rounded-full shadow-2xl flex items-center justify-center transition-all duration-300 group-hover:scale-110 group-hover:shadow-sky-400/50">
            <MessageCircle className="w-7 h-7 text-white" />
            {/* Online dot */}
            <span className="absolute top-1 right-1 w-3.5 h-3.5 bg-emerald-400 rounded-full border-2 border-white" />
            {/* Unread badge */}
            {unreadCount > 0 && (
              <span className="absolute -top-1 -left-1 w-5 h-5 bg-red-500 text-white text-xs font-bold rounded-full flex items-center justify-center">
                {Math.min(unreadCount, 9)}
              </span>
            )}
          </div>

          {/* Tooltip */}
          <div className="absolute bottom-full right-0 mb-3 px-3 py-2 bg-gray-900 text-white text-xs rounded-xl whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none shadow-xl">
            💎 Chat with Diamond Expert
            <div className="absolute top-full right-5 w-0 h-0 border-l-4 border-r-4 border-t-4 border-l-transparent border-r-transparent border-t-gray-900" />
          </div>
        </button>
      )}

      {/* ── Chat window ──────────────────────────────────────────────────── */}
      {isOpen && (
        <div
          className={`fixed z-50 flex flex-col transition-all duration-300 ease-in-out ${
            isExpanded
              ? 'inset-0 m-4'
              : 'bottom-6 right-6'
          }`}
          style={
            isExpanded
              ? { 
                  width: 'calc(100vw - 32px)',
                  height: 'calc(100vh - 32px)',
                  maxWidth: '1200px',
                  maxHeight: '90vh',
                  left: '50%',
                  top: '50%',
                  transform: 'translate(-50%, -50%)',
                }
              : {
                  width: 430,
                  maxWidth: 'calc(100vw - 24px)',
                  height: 620,
                  maxHeight: 'calc(100vh - 48px)',
                }
          }
        >
          <div
            className="flex flex-col h-full bg-white rounded-3xl overflow-hidden"
            style={{ boxShadow: '0 30px 70px rgba(0,0,0,0.18), 0 0 0 1px rgba(0,0,0,0.06)' }}
          >
            {/* Backdrop for expanded view */}
            {isExpanded && (
              <button
                onClick={() => setIsExpanded(false)}
                className="fixed inset-0 bg-black/20 -z-50 cursor-pointer"
                aria-label="Close expanded view"
              />
            )}
            {/* ── Header ─────────────────────────────────────────────────── */}
            <div className="relative flex-shrink-0 bg-gradient-to-r from-sky-500 via-blue-600 to-indigo-600 px-5 py-4">
              {/* Decorative blobs */}
              <div className="absolute inset-0 overflow-hidden pointer-events-none">
                <div className="absolute -top-8 -right-8 w-32 h-32 bg-white/10 rounded-full blur-2xl" />
                <div className="absolute -bottom-4 -left-4 w-20 h-20 bg-white/5 rounded-full blur-xl" />
              </div>

              <div className="relative flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-11 h-11 rounded-2xl bg-white/20 backdrop-blur-sm border border-white/30 flex items-center justify-center shadow-inner">
                    <Sparkles className="w-6 h-6 text-white" />
                  </div>
                  <div>
                    <h3 className="text-white font-bold leading-tight">Diamond Expert</h3>
                    <div className="flex items-center gap-1.5 mt-0.5">
                      <span className={`w-2 h-2 rounded-full ${isTyping ? 'bg-yellow-300 animate-pulse' : 'bg-emerald-400'}`} />
                      <span className="text-sky-100 text-xs">
                        {isTyping ? 'Thinking…' : 'Online · Powered by AI'}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-0.5">
                  {[
                    { Icon: RotateCcw,  action: handleClear,      title: 'New conversation' },
                    { Icon: isExpanded ? CornerDownLeft : Maximize2,  action: () => setIsExpanded(!isExpanded),  title: isExpanded ? 'Collapse' : 'Expand' },
                    { Icon: Minimize2,  action: minimizeChatbot,  title: 'Minimize' },
                    { Icon: X,          action: closeChatbot,     title: 'Close' },
                  ].map(({ Icon, action, title }) => (
                    <button
                      key={title}
                      onClick={action}
                      title={title}
                      className="p-2 text-sky-200 hover:text-white hover:bg-white/10 rounded-xl transition-colors"
                    >
                      <Icon className="w-4 h-4" />
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* ── Messages ───────────────────────────────────────────────── */}
            <div
              ref={messagesContainerRef}
              onScroll={handleScroll}
              className={`flex-1 overflow-y-auto px-4 py-4 bg-gray-50/60 ${
                isExpanded ? 'px-8 py-6' : ''
              }`}
            >
              {messages.map((msg) => (
                <MessageBubble
                  key={msg.id}
                  message={msg}
                  onSuggestionClick={handleSuggestionClick}
                  isExpanded={isExpanded}
                />
              ))}

              {isTyping && <TypingIndicator />}
              <div ref={messagesEndRef} className="h-1" />
            </div>

            {/* Scroll-to-bottom button */}
            {showScrollBtn && (
              <button
                onClick={() => scrollToBottom()}
                className="absolute bottom-[5.5rem] right-5 p-1.5 bg-white border border-gray-200 rounded-full shadow-md text-gray-500 hover:text-sky-600 hover:border-sky-300 transition-all"
              >
                <ChevronDown className="w-4 h-4" />
              </button>
            )}

            {/* ── Input ──────────────────────────────────────────────────── */}
            <div className={`flex-shrink-0 px-4 py-4 bg-white border-t border-gray-100 ${
              isExpanded ? 'px-8 py-6' : ''
            }`}>
              <div className="flex items-end gap-2">
                <textarea
                  ref={(el) => { inputRef.current = el; textareaRef.current = el; }}
                  value={inputValue}
                  onChange={(e) => { setInputValue(e.target.value); autoResize(); }}
                  onKeyDown={handleKeyDown}
                  placeholder="Ask me anything about diamonds…"
                  disabled={isLoading}
                  rows={1}
                  className="
                    flex-1 px-4 py-3 bg-gray-50 border border-gray-200 rounded-2xl
                    text-sm text-gray-800 placeholder-gray-400 resize-none leading-relaxed
                    focus:outline-none focus:ring-2 focus:ring-sky-400/50 focus:border-sky-400
                    disabled:opacity-50 transition-all
                  "
                  style={{ maxHeight: 120, overflowY: 'auto' }}
                />

                <button
                  onClick={handleSend}
                  disabled={!inputValue.trim() || isLoading}
                  className="
                    flex-shrink-0 w-11 h-11 bg-gradient-to-br from-sky-500 to-indigo-600
                    text-white rounded-2xl flex items-center justify-center shadow-md
                    hover:shadow-sky-300/50 transition-all duration-200
                    disabled:opacity-40 disabled:cursor-not-allowed
                    hover:scale-105 active:scale-95
                  "
                  aria-label="Send"
                >
                  {isLoading
                    ? <Loader2 className="w-5 h-5 animate-spin" />
                    : <Send className="w-4 h-4 translate-x-0.5" />
                  }
                </button>
              </div>

              <p className={`text-center text-xs text-gray-400 mt-2 select-none ${
                isExpanded ? 'text-sm' : ''
              }`}>
                Powered by Gemini · LangChain · LuxeStone AI
              </p>
            </div>
          </div>
        </div>
      )}
    </>
  );
}